swagger: '2.0'
info:
  description: |
    HMIS upload Service
  version: 1.0.0
  title: HMIS upload Service
  contact:
    email: support@hslynk.com
  license:
    name: Hslynk
    url: https://github.com/hmis-api/
tags:
- name: bulk-upload
  description: Hmis bulk uploader Apis.
# schemes:
# - http
paths:
  /bulk-upload:
    get:
      tags:
      - bulk-upload
      summary: Gets uploads by status
      description: Get all the uploads by status.The possible values for status are INITIAL, INPROGRESS, ENROLLMENT ,EXIT, STAGING and ERROR.
      operationId: findUploadByStatus
      produces:
      - application/json
      - application/xml
      parameters:
      - name: status
        in: query
        description: Status values that need to be considered for filter
        required: true
        type: array
        items:
          type: string
          enum:
          - INITIAL
          - INPROGRESS
          - ENROLLMENT
          - EXIT
          - STAGING
          - ERROR
          default: available
        collectionFormat: multi
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/bulkUpload'
        400:
          description: Invalid status value
      security:
      - hmis_auth:
        - write:uploads
        - read:uploads
  /bulk-upload/{uploadId}:
    get:
      tags:
      - bulk-upload
      summary: Find bulk upload by ID
      description: Returns a single upload
      operationId: getUploadById
      produces:
      - application/json
      - application/xml
      parameters:
      - name: uploadId
        in: path
        description: Upload ID for bulkUpload.
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/bulkUpload'
        400:
          description: Invalid ID supplied
        404:
          description: Pet not found
      security:
      - api_key: []
    post:
      tags:
      - bulk-upload
      summary: Upload Hmis file by passing version in the path param.
      operationId: createUploadWithForm
      consumes:
      - application/x-www-form-urlencoded
      produces:
      - application/json
      - application/xml
      parameters:
      - name: uploadId
        in: path
        description: HUD schema version,the possible values are 401, 411,51,611,612.
        required: true
        type: integer
        format: string
      - name: file
        in: formData
        description: Updated name of the Upload
        required: false
        type: string
      responses:
        405:
          description: Invalid input
      security:
      - hmis_auth:
        - write:uploads
        - read:uploads
securityDefinitions:
  hmis_auth:
    type: oauth2
    authorizationUrl: 'https://hmislynk.com/hmis-authorization-service/rest/token'
    flow: implicit
    scopes:
      write:uploads: upload a file
      read:uploads: read the status of an upload
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  bulkUploads:
    type: object
    required:
    - bulkUpload
  bulkUpload:
    type: object
    required:
    - id
    - fileName
    - fileSize
    - hudVersion
    - dateCreated
    - projectGroupCode
    - status
    - year
    properties:
      id:
        type: integer
        format: int64
      fileName:
        type: string
        example: doggie
      fileSize:
        type: integer
        format: int64
      hudVersion:
        type: integer
        format: int64
      dateCreated:
        type: string
        example: 03/4/2019
      projectGroupCode:
        type: string
        example: XXXXXX
      year:
        type: integer
        format: int64
      status:
        type: string
        description: status of bulk upload
        enum:
        - INITIAL
        - ERROR
        - STAGING
        - LIVE
    xml:
      name: bulkUpload
# Added by API Auto Mocking Plugin
host: hslynk.com
basePath: /hmis-upload-service/rest
schemes:
 - https
 - http
