#%RAML 1.0
title: bulk upload
version: 1.0.0
protocols:
  - HTTP
baseUri: https://www.hmislynk.com/hmis-upload-service/rest
mediaType: application/json
securedBy: [oauth_2_0]
securitySchemes:
  oauth_2_0: !include security-schemes/oauth_2_0.raml
types:
  bulk_upload: !include bulk_upload.json
  bulk_upload_id: !include bulk_upload_id.json
  bulk_upload: !include bulk_upload.json
  bulk_upload_ids: !include bulk_upload_ids.json

/bulk-upload:
  get:
    description: gets a set of bulk upload
    responses:
      '200':
        body:
          application/json:
            example: !include bulk_upload_ids_example.json
      '401':
        body:
          application/json:
            example:
              message: ' Unauthorized'
            required: false
      '500':
        body:
          application/json:
            example:
              errorMessage: internal server error
            required: false
    queryParameters:
      inactive:
        required: false
        description: Filter the list of bulk upload.
        example: true
        type: boolean
  post:
    description: upload a HUD Xml/CSV file for processing.
    body:
      application/json:
        type: bulk_upload
        example: !include bulk_upload_example.json
    responses:
      '200':
        body:
          application/json:
            example: !include bulk_upload_ids_example.json
      '401':
        body:
          application/json:
            example:
              message: ' Unauthorized'
            required: false
      '500':
        body:
          application/json:
            example:
              message: Resource not foundx
            required: false


  /{bulk_upload_id}:
    uriParameters:
      bulk_upload_id: {}
    displayName: retreive
    description: 'bulk upload services for get,deactivate and delete.'
    get:
      description: retreives bulk upload  details.
      responses:
        '200':
          body:
            application/json:
              example: !include bulk_upload_example.json
        '401':
          body:
            application/json:
              example:
                message: ' Unauthorized'
              required: false
        '500':
          body:
            application/json:
              example:
                errorMessage: internal server error
              required: false
    delete:
      description: to delete bulk upload on the basis of uuid
      responses:
        '200':
          body:
            application/json:
              example:
                message: Bulk Upload successfully deleted
              required: false
        '401':
          body:
            application/json:
              example:
                message: ' Unauthorized'
              required: false
        '500':
          body:
            application/json:
              example:
                message: ' Internal Server Error - retry request'
              required: false
    put:
      description: for updating bulk upload status.
      body:
        application/json:
          type: bulk_upload_id
          example: !include bulk_upload_id_example.json
      responses:
        '200':
          body:
            application/json:
              example:
                message: Bulk Upload successfully updated
              required: false
        '401':
          body:
            application/json:
              example:
                message: ' Unauthorized'
              required: false
        '500':
          body:
            application/json:
              example:
                message: ' Internal Server Error - retry request'
              required: false
